version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "Asia/Seoul"
    target-branch: "exp"
    reviewers:
      - "junbong"
    assignees:
      - "junbong"
    commit-message:
      prefix: "[Dependency]"
    labels:
      - "dependencies"
