module.exports = {
  'arrow-parens': 'off',
  'function-paren-newline': 'off',
  'implicit-arrow-linebreak': 'off',
  'import/no-dynamic-require': 'off',
  'import/no-named-as-default-member': 'off',
  'import/no-named-as-default': 'off',
  'jsx-a11y/alt-text': 'off',
  'jsx-a11y/click-events-have-key-events': 'off',
  'jsx-a11y/no-static-element-interactions': 'off',
  'no-restricted-syntax': 'off',
  'object-curly-newline': 'off',
  'operator-linebreak': 'off',
  'prefer-destructuring': 'off',
  'react/jsx-one-expression-per-line': 'off',
  'react/jsx-tag-spacing': 'off',
}